title: <p align="center"> Jignesh Shinde </p>
logo: /assets/img/jignesh.jpg
description: 
Currently working in Medtric as Field tecnical Services Specialist. 
Looking after HUGO RAS surgical robots service. 
previously worked in GE Healthcare.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
