title: <p align="center"> Jignesh Shinde </p>
logo: /assets/img/jignesh.jpg
description:
<p align="center">
<a href="pdf/resume.pdf">Resume</a> |
<a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
<a href="https://github.com/sajankedia">GitHub</a>
  
<br> 
Currently working in Medtric as Field tecnical Services Specialist. 
Looking after HUGO RAS surgical robots service. 
previously worked in GE Healthcare.
<br>
</p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
